all:
	bash lab1/script.sh
	bash lab2/script.sh
	bash lab3/script.sh
	bash lab4/script.sh
	bash lab5/script.sh

1:
	bash lab1/script.sh

2: 1
	bash lab2/script.sh

3: 2
	bash lab3/script.sh

4: 3
	bash lab4/script.sh

5: 4
	bash lab5/script.sh
