all: server client

server: lab2zrpN3250_server.c
	gcc -o lab2zrpN3250_server lab2zrpN3250_server.c -Wall -Wextra -Werror -O3

client: lab2zrpN3250_client.c
	gcc -o lab2zrpN3250_client lab2zrpN3250_client.c -Wall -Wextra -Werror -O3

clean:
	rm -f lab2zrpN3250_server lab2zrpN3250_client