all:
	gcc -o lab1zrpN3250 lab1zrpN3250.c -ldl -Wall -Wextra -Werror -O3
	gcc -shared -fPIC -o libzrpN3250.so libzrpN3250.c -Wall -Wextra -Werror -O3

clean:
	rm -rf *.o lab1zrpN3250 libzrpN3250.so
	
